//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataFileRepository.Infrastructure.ODataExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODataFileRepository.Infrastructure.ODataExtensions.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested range for the specified media resource is not satisfiable..
        /// </summary>
        internal static string ControllerRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("ControllerRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When specified, the range for the requested media resource must be 0 - {0:N0} and the From index must be less than the To index..
        /// </summary>
        internal static string ControllerRangeNotSatisfiableErrorCode {
            get {
                return ResourceManager.GetString("ControllerRangeNotSatisfiableErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a media resource is not supported for this entity set..
        /// </summary>
        internal static string ControllerUnsupportedCreateMediaResource {
            get {
                return ResourceManager.GetString("ControllerUnsupportedCreateMediaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting link failed..
        /// </summary>
        internal static string ControllerUnsupportedDeleteLinkErrorCode {
            get {
                return ResourceManager.GetString("ControllerUnsupportedDeleteLinkErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a media resource is not supported for this entity set..
        /// </summary>
        internal static string ControllerUnsupportedDeleteMediaResource {
            get {
                return ResourceManager.GetString("ControllerUnsupportedDeleteMediaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requests are not supported..
        /// </summary>
        internal static string ControllerUnsupportedMethodErrorCode {
            get {
                return ResourceManager.GetString("ControllerUnsupportedMethodErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating a media resource is not supported for this entity set..
        /// </summary>
        internal static string ControllerUnsupportedUpdateMediaResource {
            get {
                return ResourceManager.GetString("ControllerUnsupportedUpdateMediaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string ErrorMessageLanguage {
            get {
                return ResourceManager.GetString("ErrorMessageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Location header could not be generated because the request&apos;s OData path does not start with an entity set path segment..
        /// </summary>
        internal static string LocationHeaderDoesNotStartWithEntitySet {
            get {
                return ResourceManager.GetString("LocationHeaderDoesNotStartWithEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Location header could not be generated because the request does not have an associated OData path..
        /// </summary>
        internal static string LocationHeaderMissingODataPath {
            get {
                return ResourceManager.GetString("LocationHeaderMissingODataPath", resourceCulture);
            }
        }
    }
}
